# Python CircleCI 2.1 configuration file
#
# Check https://circleci.com/docs/2.1/language-python/ for more details
#
version: 2.1
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:3.7.2

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            pip install -r requirements.txt

      - save_cache:
          key: v1-dependencies-{{ checksum "requirements.txt" }}
          paths:
            - "/usr/local/lib/python3.7/site-packages"
            - "/usr/local/bin"
  
      - run:
          name: run tests
          command: |
            pip install -r test_requirements.txt
            coverage run -m pytest
            coverage report --omit=**site-packages**
            coverage xml -o test-results/xml-report

      - store_test_results:
          path: test-results
      - store_artifacts:
          path: artifacts
